{{- if .Values.deployments -}}
{{- range .Values.deployments }}
{{- with .serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | default $.Release.Name }}
  labels:
    {{- include "coatrack.labels" (merge . $) | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name | default $.Release.Name }}-rolebinding
  labels:
    {{- include "coatrack.labels" (merge . $) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .name | default $.Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .name | default $.Release.Name }}-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name | default $.Release.Name }}-role
  labels:
    {{- include "coatrack.labels" (merge . $) | nindent 4 }}
rules:
  {{- .rules | toYaml | nindent 2}}
{{- end }}
{{- end }}
{{- end }}
