{{- if .Values.bizEcosystemRss.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bizEcosystemRss.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "bizEcosystemRss.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.bizEcosystemRss.deployment.replicaCount }}
  revisionHistoryLimit: {{ .Values.bizEcosystemRss.deployment.revisionHistoryLimit }}
  strategy:
  {{- with .Values.bizEcosystemRss.deployment.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bizEcosystemRss.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "bizEcosystemRss.labels" . | nindent 8 }}
        {{- with .Values.bizEcosystemRss.deployment.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.bizEcosystemRss.deployment.additionalAnnotations -}}
      annotations:
        {{- with .Values.bizEcosystemRss.deployment.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.openshift }}
      serviceAccountName: {{ include "business-api-ecosystem.name" . }}-sa
      {{- else }}
      serviceAccountName: {{ include "bizEcosystemRss.serviceAccountName" . }}
      {{- end }}
      initContainers:
        {{- include "business-api-ecosystem.initContainer.mysql" ( dict "ctx" . "name" "{{ include \"bizEcosystemRss.fullname\" . }}" "host" .Values.bizEcosystemRss.db.host ) | nindent 8 }}
        {{- include "business-api-ecosystem.initContainer.apis" ( dict "ctx" . "name" "{{ include \"bizEcosystemRss.apiInitContainer\" . }}-inventory" "path" "DSProductInventory" ) | nindent 8 }}
        {{- include "business-api-ecosystem.initContainer.apis" ( dict "ctx" . "name" "{{ include \"bizEcosystemRss.apiInitContainer\" . }}-catalog" "path" "DSProductCatalog" ) | nindent 8 }}
        {{- include "business-api-ecosystem.initContainer.apis" ( dict "ctx" . "name" "{{ include \"bizEcosystemRss.apiInitContainer\" . }}-ordering" "path" "DSProductOrdering" ) | nindent 8 }}
        {{- include "business-api-ecosystem.initContainer.apis" ( dict "ctx" . "name" "{{ include \"bizEcosystemRss.apiInitContainer\" . }}-party" "path" "DSPartyManagement" ) | nindent 8 }}
        {{- include "business-api-ecosystem.initContainer.apis" ( dict "ctx" . "name" "{{ include \"bizEcosystemRss.apiInitContainer\" . }}-billing" "path" "DSBillingManagement" ) | nindent 8 }}
        {{- include "business-api-ecosystem.initContainer.apis" ( dict "ctx" . "name" "{{ include \"bizEcosystemRss.apiInitContainer\" . }}-customer" "path" "DSCustomerManagement" ) | nindent 8 }}
        {{- include "business-api-ecosystem.initContainer.apis" ( dict "ctx" . "name" "{{ include \"bizEcosystemRss.apiInitContainer\" . }}-usage" "path" "DSUsageManagement" ) | nindent 8 }}
      containers:
        - name: {{ template "business-api-ecosystem.name" . }}-{{ .Values.bizEcosystemRss.name }}
          imagePullPolicy: {{ .Values.bizEcosystemRss.deployment.image.pullPolicy }}
          image: "{{ .Values.bizEcosystemRss.deployment.image.repository }}:{{ .Values.bizEcosystemRss.deployment.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.bizEcosystemRss.port}}
              protocol: TCP
          {{- with .Values.bizEcosystemRss.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - /glassfish4/glassfish/bin/asadmin
                - show-component-status
                - DSRevenueSharing
            initialDelaySeconds: {{ .Values.bizEcosystemRss.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.bizEcosystemRss.deployment.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.bizEcosystemRss.deployment.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.bizEcosystemRss.deployment.livenessProbe.timeoutSeconds }}
          readinessProbe:
            exec:
              command:
                - /glassfish4/glassfish/bin/asadmin
                - show-component-status
                - DSRevenueSharing
            initialDelaySeconds: {{ .Values.bizEcosystemRss.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.bizEcosystemRss.deployment.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.bizEcosystemRss.deployment.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.bizEcosystemRss.deployment.readinessProbe.timeoutSeconds }}
          env:
            - name: MYSQL_HOST
              value: {{ .Values.bizEcosystemRss.db.host | quote }}
            - name: MYSQL_PORT
              value: {{ .Values.bizEcosystemRss.db.port | quote }}
            - name: BAE_RSS_DATABASE_URL
              value: {{ .Values.bizEcosystemRss.db.url | quote }}
            - name: BAE_RSS_DATABASE_USERNAME
              value: {{ .Values.bizEcosystemRss.db.user | quote }}
            - name: BAE_RSS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                   name: {{ include "bizEcosystemRss.secretName" . }}
                   key: dbPassword
            - name: BAE_RSS_DATABASE_DRIVERCLASSNAME
              value: {{ .Values.bizEcosystemRss.db.driver | quote }}
            - name: BAE_RSS_OAUTH_CONFIG_GRANTEDROLE
              value: {{ .Values.oauth.grantedrole | quote }}
            - name: BAE_RSS_OAUTH_CONFIG_SELLERROLE
              value: {{ .Values.oauth.sellerrole | quote }}
            - name: BAE_RSS_OAUTH_CONFIG_AGGREGATORROLE
              value: {{ .Values.oauth.aggregatorrole | quote }}
      {{- with .Values.bizEcosystemRss.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bizEcosystemRss.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bizEcosystemRss.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
{{- end }}
