{{- if and (.Values.bizEcosystemRss.enabled) (not .Values.bizEcosystemRss.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bizEcosystemRss.fullname" . }}
  labels:
    {{ include "bizEcosystemRss.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.bizEcosystemRss.db.password | b64enc }}
{{- end }}
