{{- if and .Values.bizEcosystemRss.enabled .Values.bizEcosystemRss.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bizEcosystemRss.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace | quote }}
{{- if .Values.bizEcosystemRss.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.bizEcosystemRss.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "bizEcosystemRss.labels" . | nindent 4 }}
{{- end }}
