apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pap.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "pap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
  {{- with .Values.deployment.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pap.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "pap.labels" . | nindent 8 }}
        {{- with .Values.deployment.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.deployment.additionalAnnotations -}}
      annotations:
        prometheus.io/scrape: {{ .Values.management.prometheus.enabled | quote }}
        prometheus.io/path: /q/metrics
        prometheus.io/port: {{ .Values.management.port }}
        {{- with .Values.deployment.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec: 
      serviceAccountName: {{ include "pap.serviceAccountName" . }}
      {{- if .Values.deployment.initContainers }}
      initContainers:
        {{- with .Values.deployment.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          {{- if .Values.deployment.command }}
          command:
          {{- with .Values.deployment.command }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.deployment.args }}
          args: 
          {{- with .Values.deployment.args }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port}}
              protocol: TCP
            - name: http-health
              containerPort: {{ .Values.management.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http-health
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http-health
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          env:
            - name: QUARKUS_HTTP_PORT
              value: {{ .Values.deployment.port | quote }}
            - name: QUARKUS_MANAGEMENT_PORT
              value: {{ .Values.management.port | quote }}
            {{- if .Values.management.prometheus.enabled }}
            - name: QUARKUS_MICROMETER_EXPORT_PROMETHEUS_ENABLED
              value: {{ .Values.management.prometheus.enabled | quote }}
            {{- end }}
            - name: QUARKUS_DATASOURCE_USERNAME
              value: {{ .Values.database.username | quote }}
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pap.secretName" . }}
                  key: {{ include "pap.passwordKey" . }}
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: {{ .Values.database.url | quote }}
            {{- if .Values.additionalMapping.enabled }}
            - name: PATHS_MAPPING
              value: /mappings/mapping.json
            {{- end }}
            {{- if .Values.additionalRego.enabled }}
            - name: PATHS_REGO
              value: /rego-packages
            {{- end }}
            {{- with .Values.additionalEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.additionalMapping.enabled }}
            - name: mappings
              mountPath: /mappings
            {{- end }}
            {{- if .Values.additionalRego.enabled }}
            - name: rego
              mountPath: /rego-packages
            {{- end }}
            {{- if .Values.deployment.additionalVolumeMounts }}
            {{- with .Values.deployment.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      volumes:
        {{- if .Values.additionalMapping.enabled }}
        - name: mappings
          configMap:
            name: {{ include "pap.fullname" . }}-mapping
        {{- end }}
        {{- if .Values.additionalRego.enabled }}
        - name: rego
          configMap:
            name: {{ include "pap.fullname" . }}-rego
        {{- end }}
        {{- if .Values.deployment.additionalVolumes }}
        {{- with .Values.deployment.additionalVolumes }}
        {{- toYaml . | nindent 6 }}
        {{- end }}
        {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
