{{- if not .Values.database.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pap.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "pap.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}
{{- end }}
