{{- if .Values.auth.token }}
{{- include "fiwareCommon.secret.tpl" (dict
      "context"        $
      "existingSecret" .Values.auth.existingSecret
      "data"           (dict "authToken" .Values.auth.token)) }}
{{- end }}
