{{- if .Values.umbrella.jws.root_ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-umbrella.fullname" . }}-rootca
  labels:
    {{- include "api-umbrella.labels" . | nindent 4 }}
type: Opaque
data:
  rootCA.pem: |-
    {{ .Values.umbrella.jws.root_ca | b64enc | nindent 4 }}
{{- end }}