{{- if .Values.broker.db.auth }}
{{- include "common.secret.tpl" (dict
      "context"        $
      "existingSecret" .Values.broker.db.existingSecret
      "data"           (dict "dbPassword" .Values.broker.db.auth.password)) }}
{{- end }}
