{{- if and (eq .Values.registration.enabled true) (.Values.registration) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccs.fullname" . }}-registration
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "ccs.labels" . | nindent 4 }}
data:
  init.sh: |-
    set -e  # Exit on error
    {{- if .Values.registration.prepScript }}
    # Prep script
    {{ .Values.registration.prepScript }} 
    {{- end }}
  
    # credentials config service registration
    {{- range .Values.registration.services }}

    curl -f -X 'POST' \
      'http://{{ include "ccs.fullname" $ }}:{{ $.Values.service.port }}/service' \
      -H 'accept: */*' \
      -H 'Content-Type: application/json' \
      -d @- <<EOF
      {
        "id": {{ .id | quote }},
        "defaultOidcScope": "{{ .defaultOidcScope }}",
        "oidcScopes": {{ .oidcScopes | toJson }}
      }
      EOF
    {{- end }}

{{- end }}
