{{- if .Values.route.enabled -}}
{{- $fullName := include "ccs.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ccs.fullname" . }}-ccs
  labels:
    {{ include "ccs.labels" . | nindent 4 }}
  {{- if or .Values.route.annotations .Values.route.annotations }}
  annotations:
    {{- if .Values.route.certificate }}
    cert-uccss-operator.redhat-cop.io/certs-from-secret: {{ include "ccs.fullname" . }}-tls-sec
    {{- end }}
    {{- with .Values.route.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host}}
  {{- end }}
  path: /issuer
  to:
    kind: Service
    name: {{ $fullName }}
  {{- if .Values.route.tls }}
  tls:
  {{- with .Values.route.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}