# Default values for scorpioBroker-aaio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- initial number of target replications, can be different if autoscaling is enabled
replicaCount: 1

## configuration of the image to be used
image:
  # -- scorpiobroker image name
  #ref: https://hub.docker.com/r/scorpiobroker/scorpio      
  repository: scorpiobroker/scorpio
  # -- specification of the image pull policy
  pullPolicy: IfNotPresent
  # -- tag of the image to be used
  tag: scorpio-aaio_latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# -- if a scorpio specific service account should be used, it can be configured here
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## configuration for the k8s service to access scorpiobroker
service:
  # -- service type      
  type: NodePort
  # -- port to be used by the service
  port: 9090

## ingress configuration  
ingress:
  # -- should there be an ingress to connect scorpio with the public internet      
  enabled: false
  # -- annotations to be added to the ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- all hosts to be provided  
  hosts:
      # -- provide a hosts and the paths that should be available    
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

db:
  # -- host of the database to be used
  dbhost: ngb
  # -- user for connecting the database
  user: ngb
  # -- password for connecting the database
  password: ngb
    
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
## pod autoscaling configuration, use for automatic scaling of the broker pods
autoscaling:
  # -- should autoscaling be enabled      
  enabled: false
  # -- minimum number of running pods
  minReplicas: 1
  # -- maximum number of running pods
  maxReplicas: 100
  # -- target average CPU utilization over all the pods
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
# -- selector template
# ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}
# -- tolerations template
# ref: ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
# -- affinity template
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
