apiVersion: v1
kind: Service
metadata:
  name: {{ include "vcverifier.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{ include "vcverifier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: backend
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "vcverifier.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}