apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ishare-satellite.fullname" . }}
  labels:
    {{- include "ishare-satellite.labels" . | nindent 4 }}
data:
  satellite.yml: |-
    {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
