{{- if .Values.sidecarInjector.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "sidecarInjector.name" . }}-ca-issuer
  labels:
    {{ include "sidecarInjector.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "sidecarInjector.name" . }}-secret
{{- end }}