{{- if .Values.configService.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "configService.fullname" . }}
  labels:
    {{ include "configService.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "configService.fullname" . }}
  minReplicas: {{ .Values.configService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.configService.autoscaling.maxReplicas }}
{{- with .Values.configService.autoscaling.metrics }}
  metrics: 
    {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}