{{- if .Values.ishare.enabled }}
{{- if .Values.ishare.persistence }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ishare.fullname" . }}
  {{- with .Values.ishare.annotations  }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "ishare.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ishare.storage.size | quote }}