apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "configService.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount 
    name: {{ include "configService.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "configService.serviceAccountName" . }}