{{- if .Values.sidecarInjector.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sidecarInjector.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sidecarInjector.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sidecarInjector.fullname" . }}
{{ end -}}