apiVersion: v1
kind: Secret
metadata:
  name: {{ include "configService.fullname" . }}
  labels:
    {{ include "configService.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.configService.db.password | b64enc }}