apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-service.fullname" . }}
  labels:
    {{ include "config-service.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.config-service.db.password | b64enc }}