{{- if .Values.sidecarInjector.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sidecarInjector.name" . }}-secret
  # the secret needs to be in the same namespaces as the handling cert-manager
  namespace: {{ .Values.sidecarInjector.certManagerNamespace }}
  labels:
    {{ include "sidecarInjector.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.sidecarInjector.cert | b64enc }}
  tls.key: |
    {{ .Values.sidecarInjector.key | b64enc }}
{{- end }}