{{- if .Values.ishare.enabled -}}
{{- if .Values.ishare.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ishare.fullname" . }}
{{- if .Values.ishare.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.ishare.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "ishare.labels" . | nindent 4 }}
  {{- end }}
  {{- end }}