{{- if .Values.sidecarInjector.enabled -}}
{{- if .Values.sidecarInjector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sidecarInjector.fullname" . }}
{{- if .Values.sidecarInjector.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.sidecarInjector.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "sidecarInjector.labels" . | nindent 4 }}
{{- end }}
{{- end }}