{{- if .Values.configService.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "configService.fullname" . }}
{{- if .Values.configService.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.configService.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "configService.labels" . | nindent 4 }}
{{- end }}