{{- if .Values.providerRegistry.persistent }}
{{- include "fiwareCommon.secret.tpl" (dict
      "context"        $
      "existingSecret" .Values.providerRegistry.database.existingSecret
      "data"           (dict "password" .Values.providerRegistry.database.password)) }}
{{- end }}
