apiVersion: v1
kind: Secret
metadata:
  name: {{ include "biz-ecosystem-apis.fullname" . }}
  labels:
    {{ include "biz-ecosystem-apis.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.db.password | b64enc }}
