## Default values for keyrock.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

# -- option to override the name config in the _helpers.tpl
nameOverride: ""
# -- option to override the fullname config in the _helpers.tpl
fullnameOverride: ""

## configuration for the k8s service to access keyrock
service:
  # -- service type
  type: ClusterIP
  # -- port to be used by the service
  port: 8080
  # -- addtional annotations, if required
  annotations: {}

# -- if a keyrock specific service account should be used, it can be configured here
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  # -- specifies if the account should be created
  create: false

## deployment specific configuration
deployment:
  # -- initial number of target replications, can be different if autoscaling is enabled
  replicaCount: 1
  # -- number of old replicas to be retained
  revisionHistoryLimit: 3
  ## configuration of the keyrock update strategy
  updateStrategy:
    # -- type of the update
    type: RollingUpdate
    # -- new pods will be added gradually
    rollingUpdate:
      # -- number of pods that can be created above the desired amount while updating
      maxSurge: 1
      # -- number of pods that can be unavailable while updating
      maxUnavailable: 0
  ## configuration of the image to be used
  image:
    # -- keyrock image name
    # ref: https://hub.docker.com/r/fiware/idm
    repository: fiware/idm
    # -- tag of the image to be used
    tag: 7.9.0
    # -- specification of the image pull policy
    pullPolicy: IfNotPresent
  # -- additional labels for the deployment, if required
  additionalLabels: {}
  # -- additional annotations for the deployment, if required
  additionalAnnotations: {}
  ## keyrock resource requests and limits, we leave the default empty to make that a concious choice by the user.
  ## for the autoscaling to make sense, you should configure this.
  # resources:
    # limits:
      # cpu: 100m
      # memory: 128Mi
    # requests:
      # cpu: 100m
      # memory: 128Mi
  # -- selector template
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}
  # -- tolerations template
  # ref: ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []
  # -- affinity template
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  ## liveness and readiness probes of the keyrock broker, they will be evaluated against the version endpoint
  # ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 30
  readinessProbe:
    initialDelaySeconds: 31
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 30

## pod autoscaling configuration, use for automatic scaling of the broker pods
autoscaling:
  #  -- should autoscaling be enabled for keyrock
  enabled: false
  # -- minimum number of running pods
  minReplicas: 1
  # -- maximum number of running pods
  maxReplicas: 10
  # -- metrics to react on
  metrics: []
  ## List of MetricSpecs to decide whether to scale
  # See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#metricspec-v2beta2-autoscaling
  # scaler targets to hold average cpu around 80%
  #- type: Resource
  #  resource:
  #    name: cpu
  #     target:
  #      type: Utilization
  #      averageUtilization: 80
  ## scaler targets to hold average memory around 80%
  #  - type: Resource
  #    resource:
  #      name: memory
  #      target:
  #        type: Utilization
  #        averageUtilization: 80

## openshift specific route definition. Will not work on plain k8s
route:
  ## -- should the deployment create openshift routes
  enabled: false
  # -- annotations to be added to the route
  annotations: {}
  # -- host to be used
  # host: localhost
  # -- tls configuration for the route
  tls: {}
  # termination: edge

## ingress configuration
ingress:
  # -- should there be an ingress to connect keyrock with the public internet
  enabled: false
  # -- annotations to be added to the ingress
  annotations: {}
    # kubernetes.io/ingress.class: "ambassador"
    ## example annotations, allowing cert-manager to automatically create tls-certs and forcing everything to use ssl.
    # kubernetes.io/tls-acme: "true"
    # ingress.kubernetes.io/ssl-redirect: "true"
  # -- all hosts to be provided
  hosts: []
    ## provide a hosts and the paths that should be available
    # - host: localhost
      # paths:
      # - /
  # -- configure the ingress' tls
  tls: []
    # - secretName: keyrock-tls
      # hosts:
        # - keyrock.fiware.org

# -- port that the keyrock container uses
port: 8080
# -- host where keyrock is available at
host: http://localhost
## database configuration for keyrock
db:
  # -- host of the database to be used
  host: mysql
  # -- user for connecting the database
  user: root
  # -- password for connecting the database
  password: pass
## admin configuration for accessing keyrock
admin:
  # -- username of the initial keyrock admin
  user: admin
  # -- password of the initial admin, leave empty to get a generated one
  password: admin
  # -- email address of the admin user
  email: admin@admin.org
## Theme configuration for Keyrock
theme:
  ## -- Enable theme
    enabled: false
    ## -- Name of the theme
    name: default
    ## -- Size of PVCs to be created
    size: 50Mi
    ## -- PVC Annotations
    annotations: {}
    ## Image which holds the theme files
    image: my-theme-image:latest
    ## -- specification of the image pull policy
    imagePullPolicy: IfNotPresent
    ## Path to the source theme files inside the container
    sourceTheme: /themes/my-theme
    ## Path to the source image files inside the container
    sourceImg: /img/my-theme
    ## Optional: Path to the source favicon directory inside the container
    #sourceFavicon: /favicon
    ## Mount path for the source theme files
    mountTheme: /opt/fiware-idm/themes/my-theme
    ## Mount path for the source image files
    mountImg: /opt/fiware-idm/public/img/my-theme
    ## Mount path for the source favicon
    mountFavicon: /opt/fiware-idm/public/favicon.ico
    
# -- a list of additional env vars to be set, check the keyrock docu for all available options
# ref: https://fiware-idm.readthedocs.io/en/latest/installation_and_administration_guide/environment_variables/index.html
additonalEnvVars: []
# - name: IDM_TITLE
#   value: MyKeyrock



