{{- if .Values.bizEcosystemApis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bizEcosystemApis.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "bizEcosystemApis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.bizEcosystemApis.deployment.replicaCount }}
  revisionHistoryLimit: {{ .Values.bizEcosystemApis.deployment.revisionHistoryLimit }}
  strategy:
  {{- with .Values.bizEcosystemApis.deployment.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bizEcosystemApis.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "bizEcosystemApis.labels" . | nindent 8 }}
        {{- with .Values.bizEcosystemApis.deployment.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.bizEcosystemApis.deployment.additionalAnnotations -}}
      annotations:
        {{- with .Values.bizEcosystemApis.deployment.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.openshift }}
      serviceAccountName: {{ include "business-api-ecosystem.name" . }}-sa
      {{- else }}
      serviceAccountName: {{ include "bizEcosystemApis.serviceAccountName" . }}
      {{- end }}
      initContainers:
        {{- include "business-api-ecosystem.initContainer.mysql" ( dict "ctx" . "name" "{{ include \"bizEcosystemApis.fullname\" . }}" "host" .Values.bizEcosystemApis.db.host ) | nindent 8 }}          
      containers:
        - name: {{ template "business-api-ecosystem.name" . }}-{{ .Values.bizEcosystemApis.name }}
          imagePullPolicy: {{ .Values.bizEcosystemApis.deployment.image.pullPolicy }}
          image: '{{ .Values.bizEcosystemApis.deployment.image.repository }}:{{ .Values.bizEcosystemApis.deployment.image.tag }}'
          ports:
            - name: http
              containerPort: {{ .Values.bizEcosystemApis.port}}
              protocol: TCP
          {{- with .Values.bizEcosystemApis.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /DSProductInventory
              port: {{ .Values.bizEcosystemApis.port }}
            initialDelaySeconds: {{ .Values.bizEcosystemApis.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.bizEcosystemApis.deployment.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.bizEcosystemApis.deployment.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.bizEcosystemApis.deployment.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /DSProductInventory
              port: {{ .Values.bizEcosystemApis.port }}
            initialDelaySeconds: {{ .Values.bizEcosystemApis.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.bizEcosystemApis.deployment.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.bizEcosystemApis.deployment.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.bizEcosystemApis.deployment.readinessProbe.timeoutSeconds }}
          env:
            - name: MYSQL_HOST
              value: {{ .Values.bizEcosystemApis.db.host | quote }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                   name: {{ include "bizEcosystemApis.secretName" . }}
                   key: dbPassword
            - name: BAE_SERVICE_HOST
              value: http://{{ include "bizEcosystemLogicProxy.fullhostname" . }}
      {{- with .Values.bizEcosystemApis.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bizEcosystemApis.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bizEcosystemApis.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
{{- end }}
