{{- if and (.Values.bizEcosystemApis.enabled) (not .Values.bizEcosystemApis.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bizEcosystemApis.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "bizEcosystemApis.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.bizEcosystemApis.db.password | b64enc | quote }}
{{- end }}
