{{- if .Values.atContextServer.enabled }}
{{- include "common.service.tpl" (dict
      "context" $
      "component" .Values.atContextServer.name
      "service" .Values.atContextServer.service
      "ports"   (list (dict
                        "port" .Values.atContextServer.service.port
                        "name" (quote .Values.atContextServer.service.port)))) }}
{{- end }}
