{{- if .Values.atContextServer.enabled }}
{{- include "fiwareCommon.hpa.tpl" (dict
      "context"     $
      "component"   .Values.atContextServer.name
      "autoscaling" .Values.atContextServer.autoscaling) }}
{{- end }}
