{{- if .Values.configServer.enabled }}
{{- include "common.service.tpl" (dict
      "context" $
      "component" .Values.configServer.name
      "service" .Values.configServer.service
      "ports"   (list (dict
                        "port" .Values.configServer.service.port
                        "name" (quote .Values.configServer.service.port)))) }}
{{- end }}
