{{- if .Values.configServer.enabled }}
{{- include "fiwareCommon.hpa.tpl" (dict
      "context"     $
      "component"   .Values.configServer.name
      "autoscaling" .Values.configServer.autoscaling) }}
{{- end }}
