{{- if .Values.entityManager.enabled }}
{{- include "fiwareCommon.service.tpl" (dict
      "context" $
      "component" .Values.entityManager.name
      "service" .Values.entityManager.service
      "ports"   (list (dict
                        "port" .Values.entityManager.service.port
                        "name" (quote .Values.entityManager.service.port)))) }}
{{- end }}
