{{- if .Values.entityManager.enabled }}
{{- include "fiwareCommon.hpa.tpl" (dict
      "context"     $
      "component"   .Values.entityManager.name
      "autoscaling" .Values.entityManager.autoscaling) }}
{{- end }}
