{{- if .Values.historyManager.enabled }}
{{- include "common.service.tpl" (dict
      "context" $
      "component" .Values.historyManager.name
      "service" .Values.historyManager.service
      "ports"   (list (dict
                        "port" .Values.historyManager.service.port
                        "name" (quote .Values.historyManager.service.port)))) }}
{{- end }}
