{{- if .Values.historyManager.enabled }}
{{- include "fiwareCommon.hpa.tpl" (dict
      "context"     $
      "component"   .Values.historyManager.name
      "autoscaling" .Values.historyManager.autoscaling) }}
{{- end }}
