{{- if .Values.queryManager.enabled }}
{{- include "fiwareCommon.service.tpl" (dict
      "context" $
      "component" .Values.queryManager.name
      "service" .Values.queryManager.service
      "ports"   (list (dict
                        "port" .Values.queryManager.service.port
                        "name" (quote .Values.queryManager.service.port)))) }}
{{- end }}
