{{- if .Values.queryManager.enabled }}
{{- include "fiwareCommon.hpa.tpl" (dict
      "context"     $
      "component"   .Values.queryManager.name
      "autoscaling" .Values.queryManager.autoscaling) }}
{{- end }}
