{{- if .Values.registryManager.enabled }}
{{- include "common.service.tpl" (dict
      "context" $
      "component" .Values.registryManager.name
      "service" .Values.registryManager.service
      "ports"   (list (dict
                        "port" .Values.registryManager.service.port
                        "name" (quote .Values.registryManager.service.port)))) }}
{{- end }}
