{{- if .Values.registrySubscriptionManager.enabled }}
{{- include "common.service.tpl" (dict
      "context" $
      "component" .Values.registrySubscriptionManager.name
      "service" .Values.registrySubscriptionManager.service
      "ports"   (list (dict
                        "port" .Values.registrySubscriptionManager.service.port
                        "name" (quote .Values.registrySubscriptionManager.service.port)))) }}
{{- end }}
