{{- if .Values.registryManager.enabled }}
{{- include "fiwareCommon.hpa.tpl" (dict
      "context"     $
      "component"   .Values.registryManager.name
      "autoscaling" .Values.registryManager.autoscaling) }}
{{- end }}
