{{- if .Values.registrySubscriptionManager.enabled }}
{{- include "fiwareCommon.hpa.tpl" (dict
      "context"     $
      "component"   .Values.registrySubscriptionManager.name
      "autoscaling" .Values.registrySubscriptionManager.autoscaling) }}
{{- end }}
