{{- if .Values.subscriptionManager.enabled }}
{{- include "fiwareCommon.service.tpl" (dict
      "context" $
      "component" .Values.subscriptionManager.name
      "service" .Values.subscriptionManager.service
      "ports"   (list (dict
                        "port" .Values.subscriptionManager.service.port
                        "name" (quote .Values.subscriptionManager.service.port)))) }}
{{- end }}
