{{- if .Values.subscriptionManager.enabled }}
{{- include "fiwareCommon.hpa.tpl" (dict
      "context"     $
      "component"   .Values.subscriptionManager.name
      "autoscaling" .Values.subscriptionManager.autoscaling) }}
{{- end }}
