{{- range $name, $deployment := .Values.deployment }}
{{- $cfg := mergeOverwrite (deepCopy $.Values.common) $deployment }}
{{- if (eq  $cfg.ingress.enabled true) -}}
---
{{- $servicePort := $cfg.service.port -}}
{{- $fullname := include "fdsc-edc.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fdsc-edc.fullname" . }}-{{ $name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "fdsc-edc.labels" . | nindent 4 }}
  {{- if $cfg.ingress.annotations }}
  annotations:
    {{- with $cfg.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  {{- if $cfg.ingress.className }}
  ingressClassName: {{ $cfg.ingress.className }}
  {{- end }}
  {{- if $cfg.ingress.tls }}
  tls:
    {{- range $cfg.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range $cfg.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-{{ $name }}
            port:
              number: {{ $servicePort }}
      {{- end }}
  {{- end }}
{{- end }}