{{- range $name, $deployment := .Values.deployment }}
{{- $cfg := mergeOverwrite (deepCopy $.Values.common) $deployment }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fdsc-edc.fullname" . }}-{{ $name }}
  namespace: {{ $.Release.Namespace | quote }}

  {{- with $cfg.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  labels:
    app.kubernetes.io/name: {{ include "fdsc-edc.fullname" . }}-{{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ include "fdsc-edc.fullname" . }}-{{ $name }}

spec:
  type: {{ $cfg.service.type }}

  ports:
    - name: http
      port: {{ $cfg.config.web.http.port }}
      targetPort: http
      protocol: TCP

    - name: http-version
      port: {{ $cfg.config.web.http.version.port }}
      targetPort: http-version
      protocol: TCP

    - name: http-protocol
      port: {{ $cfg.config.web.http.protocol.port }}
      targetPort: http-protocol
      protocol: TCP

    - name: http-catalog
      port: {{ $cfg.config.web.http.catalog.port }}
      targetPort: http-catalog
      protocol: TCP

    - name: http-management
      port: {{ $cfg.config.web.http.management.port }}
      targetPort: http-management
      protocol: TCP

    - name: http-control
      port: {{ $cfg.config.web.http.control.port }}
      targetPort: http-control
      protocol: TCP

    - name: http-tck
      port: {{ $cfg.config.testExtension.controller.port }}
      targetPort: http-tck
      protocol: TCP

  selector:
      app.kubernetes.io/name: {{ include "fdsc-edc.fullname" . }}-{{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ include "fdsc-edc.fullname" . }}-{{ $name }}

{{- end }}