{{- if .Values.bizEcosystemLogicProxy.route.enabled -}}
{{- range $index, $route := .Values.bizEcosystemLogicProxy.route.routes }}
{{- if $route.certificate -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "bizEcosystemLogicProxy.fullname" $ }}-{{ $index }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "bizEcosystemLogicProxy.labels" $ | nindent 4 }}
spec:
  secretName: {{ include "bizEcosystemLogicProxy.fullname" $ }}-tls-sec-{{ $index }}
  issuerRef: 
    {{- toYaml $route.certificate.issuer | nindent 4 }}
  commonName: {{ $route.host | quote }}
  dnsNames:
    - {{ $route.host | quote }}
---
{{- end }}
{{- end }}
{{- end -}}
