{{- if and .Values.bizEcosystemLogicProxy.enabled .Values.bizEcosystemLogicProxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bizEcosystemLogicProxy.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace | quote }}
{{- if .Values.bizEcosystemLogicProxy.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.bizEcosystemLogicProxy.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "bizEcosystemLogicProxy.labels" . | nindent 4 }}
{{- end }}
