{{- if .Values.route.certificate -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "tmforum.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "tmforum.labels" . | nindent 4 }}
spec:
  secretName: {{ include "tmforum.fullname" . }}-tls-sec
  issuerRef:
    {{- toYaml .Values.route.certificate.issuer | nindent 4 }}
  commonName: {{ .Values.route.host }}
  dnsNames:
    - {{ .Values.route.host }}
{{- end -}}