{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tmforum.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "tmforum.labels" . | nindent 4 }}
{{- end }}