{{- if .Values.openshift -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "business-api-ecosystem.name" . }}-sa
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: {{ include "business-api-ecosystem.name" . }}
    chart: {{ include "business-api-ecosystem.chart" . }}
{{- end -}}