apiVersion: v1
name: fdsc-edc
version: 0.1.4
appVersion: 0.1.6
description: A Helm chart for running the fdsc-edc on kubernetes.
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
  - fiware
  - data-space-connector
  - dataspace
  - dataspace-protocol
sources:
  - https://github.com/SEAMWARE/fdsc-edc
maintainers:
  - name: wistefan
    email: stefan.wiedemann@seamware.org
