apiVersion: v2
name: onboarding-portal
version: 1.2.6
appVersion: 0.0.5
type: application
description: A Helm chart for the OnBoarding Portal
icon: https://fiware.github.io/catalogue/img/fiware.png
maintainers:
  - name: "Miguel Ortega"
    email: "miguel.ortega@seamware.com"
keywords:
  - onboarding
  - FIWARE
  - Data Space Connector
sources:
  - https://github.com/SEAMWARE/On-Boarding-Portal
