{{- if not .Values.deployment.ishare.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dsba-pdp.fullname" . }}-ishare
  labels:
    {{ include "dsba-pdp.labels" . | nindent 4 }}
type: Opaque
data:
  certificate.pem: |-
    {{ .Values.deployment.ishare.certificate | b64enc | nindent 4 }}
  key.pem: |-
    {{ .Values.deployment.ishare.key | b64enc | nindent 4 }}
{{- end }}