{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dsba-pdp.fullname" . }}
  labels:
    {{ include "dsba-pdp.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.db.password | quote }}
{{- end }}