{{- if .Values.route.tir.enabled -}}
{{- $fullName := include "til.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "til.fullname" . }}-tir
  labels:
    {{ include "til.labels" . | nindent 4 }}
  {{- if or .Values.route.tir.annotations .Values.route.tir.certificate }}
  annotations:
    {{- if .Values.route.tir.certificate }}
    cert-utils-operator.redhat-cop.io/certs-from-secret: {{ include "til.fullname" . }}-tir-tls-sec
    {{- end }}
    {{- with .Values.route.tir.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  {{- if .Values.route.tir.host }}
  host: {{ .Values.route.tir.host}}
  {{- end }}
  path: /v4/issuers
  to:
    kind: Service
    name: {{ include "til.serviceName" . }}
  {{- if .Values.route.tir.tls }}
  tls:
  {{- with .Values.route.tir.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
