{{- include "fiwareCommon.secret.tpl" (dict
      "context"        $
      "existingSecret" (ternary .Values.database.existingSecret ""
                         .Values.database.existingSecret.enabled)
      "data"           (dict "password" .Values.database.password)) }}
