{{- include "common.secret.tpl" (dict
      "context"        $
      "existingSecret" .Values.existingSecret
      "data"           (dict "defaultAccount" .Values.deployment.defaultAccount.privateKey)) }}
