{{- if .Values.iota.authentication -}}
{{- if eq .Values.iota.authentication.identityManager.type "oauth2" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iota-json.fullname" . }}
  labels:
    {{ include "iota-json.labels" . | nindent 4 }}
type: Opaque
data:
  clientId: {{ .Values.iota.authentication.identityManager.oauth2.clientId | b64enc }}
  clientSecret: {{ .Values.iota.authentication.identityManager.oauth2.clientSecret | b64enc }}
{{- end }}
{{- end }}
