{{- if and .Values.atContextServer.enabled .Values.atContextServer.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{  include "at-context-server.fullname" . }}-hpa
 namespace: {{ .Release.Namespace }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ include "at-context-server.fullname" . }}
 minReplicas: {{ .Values.atContextServer.hpa.minReplicas }}
 maxReplicas: {{ .Values.atContextServer.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.atContextServer.hpa.targetCPUUtilizationPercentage }}
{{- end }}
