{{- if .Values.atContextServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.atContextServer.contextLabel }}
  name: {{ include "at-context-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "27015"
    port: 27015
    targetPort: 27015
  selector:
    service: {{ include "config-server.fullname" . }}
{{- end }}

