{{- if .Values.AtContextServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.AtContextServer.name }}
  name: {{ .Values.AtContextServer.name }}
  namespace: {{.Values.namespace}}
spec:
  ports:
  - name: "27015"
    port: 27015
    targetPort: 27015
  selector:
    service: {{ .Values.AtContextServer.name }}
status: {}
{{- end }}

