{{- if .Values.configServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.configServer.configLabel }}
  name: {{ include "config-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    service: {{ .Values.configServer.name }}
{{- end }}

