{{- if .Values.entityManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.entityManager.entityLabel }}
  name: {{ include "entity-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "1025"
    port: 1025
    targetPort: 1025
  selector:
    service: {{ include "entity-manager.fullname" . }}
{{- end }}
