{{- if .Values.EntityManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.EntityManager.name }}
  name: {{ .Values.EntityManager.name }}
  namespace: {{.Values.namespace}}
spec:
  ports:
  - name: "1025"
    port: 1025
    targetPort: 1025
  selector:
    service: {{ .Values.EntityManager.name }}
status: {}
{{- end }}