{{- if .Values.eureka.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.eureka.eurekaLabel }}
  name: {{ include "eureka.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    service: {{ include "eureka.fullname" . }}
{{- end }}
