{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.gateway.gatewayLabel }}
  name: {{ include "gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: {{ include "gateway.fullname" . }}
{{- end }}
