{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.gateway.gatewayLabel }}
  name: {{ include "gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gateway.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
  {{- with .Values.gateway.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        service: {{ include "gateway.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}
        imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
        name: {{ include "gateway.fullname" . }}
        ports:
        - containerPort: 9090
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT {{ .Values.gateway.eurekaAddress }}
        {{- if .Values.gateway.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:9090/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.gateway.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.gateway.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.gateway.readinessProbe.periodSeconds }}
          {{- end }}
        {{- if .Values.gateway.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:9090/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.gateway.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.gateway.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.gateway.livenessProbe.periodSeconds }}
          {{- end }}    
        resources:
{{ toYaml .Values.gateway.resources | indent 10 }}
      restartPolicy: {{ .Values.gateway.restartPolicy }}
      {{- if .Values.gateway.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.gateway.serviceAccount.name }}
      {{- end }}
      securityContext: {{ .Values.gateway.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.gateway.terminationGracePeriodSeconds }}
{{- end }}
