{{- if .Values.historyManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.historyManager.historyLabel }}
  name: {{ include "history-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "1040"
    port: 1040
    targetPort: 1040
  selector:
    service: {{ include "history-manager.fullname" . }}
{{- end }}
