{{- if .Values.queryManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.queryManager.queryLabel }}
  name: {{ include "query-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "1026"
    port: 1026
    targetPort: 1026
  selector:
    service: {{ include "query-manager.fullname" . }}
{{- end }}
