{{- if .Values.RegistryManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.RegistryManager.name }}
  name: {{ .Values.RegistryManager.name }}
  namespace: {{.Values.namespace}}
spec:
  ports:
  - name: "1030"
    port: 1030
    targetPort: 1030
  selector:
    service: {{ .Values.RegistryManager.name }}
status: {}
{{- end }}