{{- if .Values.registryManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.registryManager.registryLabel }}
  name: {{ include "registry-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "1030"
    port: 1030
    targetPort: 1030
  selector:
    service: {{ include "registry-manager.fullname" . }}
{{- end }}
