{{- if .Values.storageManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storageManager.fullname" . }}
  labels:
    {{ include "storageManager.labels" . | nindent 4 }}
spec:
  ports:
  - name: "1029"
    port: 1029
    targetPort: 1029
  selector:
    {{ include "storageManager.matchLabels" . | nindent 4 }}
{{- end }}
