{{- if .Values.subscriptionManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.subscriptionManager.subscriptionLabel }}
  name: {{ include "subscription-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "2025"
    port: 2025
    targetPort: 2025
  selector:
    service: {{ include "subscription-manager.fullname" . }}
{{- end }}
