{{- if .Values.keystores }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dss.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dss.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.keystores | nindent 2 }}
{{- end }}